### PR TITLE
Show all rules button in debug mode

### PR DESCRIPTION
**Pull request by Honny1**
This PR create a button to show details of all rules. After using debug option ```BUTTON-SHOW-ALL-RULES```.

### CODE REVIEW

**Comment by jan-cerny** [comment]
For some reason, it's extremely slow. I got the report generated from tests/test_data/arf-report.xml and it heated my laptop up. I even got the Firefox banner that this page slows down the browser. Have you experienced this? If yes, do you really want to have this button there?

**Comment by Honny1** [comment]
Yes, I have, but with more than 1000 rules in the report. I created it for testing purposes so It is not much optimized. If you think this is useful for users, I will try to resolve this issue.

**Comment by jan-cerny** [comment]
@Honny1 Interesting. So what do you want to test? Can the testing be done in a different way that by adding a user-visible button?

**Comment by Honny1** [comment]
It is used for visual testing of css, etc. Or I use it for the difference between a report generated by oscap and a report generated by oscap-report.

**Comment by Honny1** [comment]
@jan-cerny I adjusted the now button doesn't click on all those rules at once. It feels fast but it still generates HTML and It does not freeze the browser. Users see the first rules expanded immediately but expanding all rules take some time.

**Comment by jan-cerny** [comment]
@Honny1 Now I like it more, and thanks for the amazing speed-up. But, I can't hide the rule details. I click on "Show all result details" everything expands, and then I click on "Hide all result details" and nothing happens. Do you also have this problem?

**Comment by Honny1** [comment]
@jan-cerny  Yes, I have this problem but actually, it is caused by not expanding all rules yet. So you need to wait to expand all rules and then it collapses. So I disable the button til all rules are expanded.

**Comment by Honny1** [comment]
@jan-cerny  I think I found the main cause of the slowdown and freezing. It is generating of `OVAL graphs` using `jQuery` and then recalculates the entire page layout by the browser. 

I will replace `jQuery` with vanilla Javascript and improve performance in another PR.

**Review by jan-cerny — APPROVED** [review]
aha, clever!

I tried it again and now it works responsively. Amazing!

**Pull request merged**
